name: learnopengl
description: learnopengl.com for Dart
version: 1.2.0
homepage: https://github.com/sansuido/learnopengl
repository: https://github.com/sansuido/learnopengl

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  ffi: ^2.1.0
  glew: ^1.2.0
  glfw3: ^1.2.0
  image: ^4.0.17
  sdl2: ^1.7.0
  sdl3: ^0.1.1
  vector_math: ^2.1.4
